### ISSUE TITLE
gifs

### ISSUE THREAD

**Issue by horeaporutiu** [horeaporutiu/raft-fabric-samples2#8]
![createCar](https://user-images.githubusercontent.com/10428517/71459965-b2e54380-275e-11ea-9015-4701f8810909.gif)

![changeCar](https://user-images.githubusercontent.com/10428517/71459972-bb3d7e80-275e-11ea-8e31-9582edc21da8.gif)

**Comment by horeaporutiu** [comment]
![reject](https://user-images.githubusercontent.com/10428517/71500884-dd490680-281b-11ea-8205-c32018d26862.gif)
![stop5](https://user-images.githubusercontent.com/10428517/71500885-de7a3380-281b-11ea-8fcf-f0f784e2e8c9.gif)
![stop4](https://user-images.githubusercontent.com/10428517/71500886-de7a3380-281b-11ea-9843-1d47ba64b2c8.gif)

**Comment by horeaporutiu** [comment]
![raftArch](https://user-images.githubusercontent.com/10428517/71536882-5f433900-28c9-11ea-9256-df52ef85fae2.png)

**Comment by horeaporutiu** [comment]
![raftCluster](https://user-images.githubusercontent.com/10428517/71844741-b55b6d80-307b-11ea-8428-f973865d556a.png)

**Comment by horeaporutiu** [comment]
![demo](https://user-images.githubusercontent.com/10428517/71871871-76ef9e00-30cf-11ea-89cf-38557b93d2b8.png)
![setup](https://user-images.githubusercontent.com/10428517/71871873-78b96180-30cf-11ea-9e1a-d6d499c0e59a.png)

**Comment by horeaporutiu** [comment]
![angularUpdate](https://user-images.githubusercontent.com/10428517/71922429-ba81f080-313f-11ea-9884-f58064b26493.png)

**Comment by horeaporutiu** [comment]
![idk](https://user-images.githubusercontent.com/10428517/77009864-e8489a00-6925-11ea-83ee-166d379e9534.png)

**Comment by nedaa2020** [comment]
I have issue when I perform the log command:
>docker logs -f orderer4.example.com
It gives me an error message"
Error response from daemon: configured logging driver does not support reading"

How can I fix this issue?
Thanks,

![image](https://user-images.githubusercontent.com/39242998/85956297-25e1a800-b996-11ea-9b5d-d5283a4dcaee.png)
